flowchart TB
    subgraph A["TC Tx Services"]
        subgraph A1 ["Packet Processing"]
            A1s1[["storePacketTxTc(packet, packetLength, vid, mapid, serviceType)"]]
            A1s2[["packetProcessingRequestTxTC(vid, mapid, transferFrameDataLength, serviceType)<br>calls internally:<br>-segmentationTC<br>-blockingTC"]]
            A1s3[["frontUnprocessedFrameMcCopyTxTC()"]]
            A1s4[["getLastMasterCopyTcFrame()"]]
            A1s5[["backUnprocessedFrameMcCopyTxTC()"]]
            A1s6[["frontFrameBeforeSDLSProcessing(vid)"]]
            A1s7[["getFramesBeforeSDLSProcessing(vid)"]]

            subgraph MAP_AD ["MAP Type AD Buffers"]
                map4
                map5
            end

            subgraph MAP_BD ["MAP Type BD Buffers"]
                map6
                map7
            end

            subgraph VC_AD ["VC Type AD Buffers"]
                vc10
                vc11
            end

            subgraph VC_BD ["VC Type BD Buffers"]
                vc12
                vc13
            end

            MAP_AD ~~~ MAP_BD ~~~ VC_AD ~~~ VC_BD 

            A1s1 -.->|"Type AD AND segHeader exists"| MAP_AD
            A1s1 -.->|"Type BD AND segHeader exists"| MAP_BD
            A1s1 -.->|"Type AD AND segHeader not exist"| VC_AD
            A1s1 -.->|"Type BD AND segHeader not exist"| VC_BD

            A1s2 -.-x|"Type AD AND segHeader exists"| MAP_AD
            A1s2 -.-x|"Type BD AND segHeader exists"| MAP_BD
            A1s2 -.-x|"Type AD AND segHeader not exist"| VC_AD
            A1s2 -.-x|"Type BD AND segHeader not exist"| VC_BD

            A1s1 --> A1s2
            A1s2 -.->|"(from segmentation,blocking)"| master16
            A1s2 -.->|"(from segmentation,blocking)"| master12
            A1s3 -.front reference.-master12
                        A1s4 -.back reference.-master12
            A1s5 -.back reference.-master12

            A1s2 -.-> |"(from segmentation,blocking)"|vc16

            A1s6 -.front reference.-vc16
            A1s7 -.get queue reference.-vc16

        end

        subgraph A2 ["SDLS Processing"]
            A2s1[["applySecurityTxTC(vid, mapid)"]]

            A1s2 --> A2s1
            A2s1-.-x vc16
            A2s1 -.-x|deletion of AD, BD frames upon MAC computation error| master12
            A2s1 -.-x|deletion of AD, BD frames upon MAC computation error| master16
            A2s1 -.-> vc7
        end

        subgraph A3 ["Virtual Channel Generation"]
            A3s1[["vcGenerationRequestTxTC(vid)<br>Calls internally:<br>-transferFdu (fop service)"]]
            A3s2[["frontFrameBeforeAllFramesGenerationTxTC()"]]

            A2s1 --> A3s1
            A3s1 -..->|"From fop (BC frame generation)"| master12
            A3s1 -..-x|"From fop (after reception confirmation, AD and BC)"| master16
            A3s1 -.-x vc7
            A3s1 -.-> master1
            A3s2 -.-|"front reference"| master1
        end

        
        subgraph A4 ["All Frames Generation"]
            A4s1[["allFramesGenerationRequestTxTC(frameTarget)"]]
           
            A3s1 --> A4s1
            A4s1 -.-x master1
        end
    end

    A1 ~~~ A2 ~~~ A3 ~~~ A4

    subgraph B ["TC Rx Services"]
        subgraph B1["All Frames Reception"]

            B1s2[["allFramesReceptionRequestRxTC()"]]
            B1s7[["getAvailableBeforeVcReceptionRxTC(vid)"]]

            B1s2 -..-> master14
            B1s2 -..-> master20
            B1s2 -.->vc3
            B1s7 -..-|"remaining space"| vc3
        end

        subgraph B2["Virtual Channel Reception"]
            B2s1[["vcReceptionRxTC(vid)<br>calls internally:<br>frameArrives<br>(FARM)"]]
            B2s3[["getAvailableinFramesAfterVCReceptionTybeADRxTC(vid)"]]
            B2s4[["getAvailableinFramesAfterVCReceptionTybeBDRxTC(vid)"]]

            B1s2 --> B2s1
            B2s1 --->|"push CLCW to corresponding queue"| master18
            B2s1 -..->|farm insertion| vc6
            B2s1 -..->|farm insertion| vc21

            B2s1 -..-x|"farm deletion"| vc3
            B2s1 -..-x|"farm deletion (lockout state)"| master14
            B2s1 -..-x|"farm deletion (lockout state)"| master20
            B2s3 -.-|"remaining space"| vc6
            B2s4 -.-|"remaining space"| vc21
        end

        subgraph B3["SDLS Processing"]
            B3s1[["processSDLSSecurityRxTC(vid, mapid)"]]

            B2s1 --> B3s1
            B3s1 -.-x vc6
            B3s1 -.-x vc21
            B3s1 -.-x master14
            B3s1 -.-x master20

            B3s1 -.-> map8
            B3s1 -.-> map9
            B3s1 -.-> vc17
            B3s1 -.-> vc19
            
        end

        subgraph B4["Virtual Channel Extraction"]
            B4s1[["packetExtractionRxTC(vid, mapid, serviceType, packetDest)"]]

            B3s1 --> B4s1

            B4s1 -.-x map8
            B4s1 -.-x map9
            B4s1 -.-x vc17
            B4s1 -.-x vc19
            B4s1 -.-x master14
            B4s1 -...............-x master20
            
        end
    end

    subgraph C ["TM Tx Services"]
        subgraph C1["Packet Processing"]
            C1s1[["storePacketTxTM(packet, packetLength, vid)"]]
            C1s2[["availablePacketLengthBufferTxTM(gvcid)"]]
            C1s3[["availablePacketBufferTxTM(gvcid)"]]

            C1s1 -.-> vc8 & vc9
            C1s2 -.-|"available space"| vc8
            C1s3 -.-|"available space"| vc9
        end

        subgraph C2["Virtual Channel Generation"]
            C2s1[["vcGenerationServiceTxTM(transferFrameDataFieldLength, vid) <br> calls internally:<br>-segmentationTM<br>-blockingTM<br>-generateacket"]]
            C2s2[["availableFramesAfterVcGenerationTxTM()"]]
            C2s3[["backFrameAfterVcGenerationTxTM()"]]
            C2s4[["frontFrameAfterVcGenerationTxTM()"]]


            C1s1 --> C2s1
            C2s1 -.-x|"(from segmentation,blocking)"| vc8 & vc9
            C2s1 -.->|"(from segmentation,blocking)"| master13 & master11 & master17
            C2s2 -.-|"remaining space"| master11
            C2s3 -.-|"back reference"| master11
            C2s4 -.-|"front reference"| master11
            end

        subgraph C3["Master Channel Generation"]
            C3s1[["mcGenerationRequestTxTM()"]]

            C2s1 --> C3s1
            C3s1 -.-> master4
            C3s1 -.-x master11
            C3s1 -.-x|"Pop CLCWs from buffers<br>(if ocf field exists)"| master19
        end

        subgraph C4["All Frames Generation"]
            C4s1[["allFramesGenerationRequestTxTM(frameDataTarget)"]]

            C3s1 --> C4s1
            C4s1 -.-x master4 & master17 & master13
        end
    end

    subgraph D["TM Rx Services"]
        subgraph D1["All Frames Reception"]
            D1s1[["allFramesReceptionRequestRxTM(frameData, frameLength)"]]
            D1s2[["availableFramesVcCopyRxTM(vid)"]]
            D1s3[["availableFramesMcCopyRxTM()"]]

            D1s1 -.-> master15 & vc1
            D1s2 -.-|remaining space| vc1
            D1s3 -.-|remaining space| master15
        end

        subgraph D2["Packet Extraction"]
            D2s1[["packetExtractionRxTM(vid, packetTarget)"]]
            D1s1 --> D2s1
            D2s1 -.-x master15 & vc1
        end
    end

    subgraph E["Legend"]
        E1[[Necessary Service]]
        E2[[Service for Debugging/Utility]]
        E3[(MAP Channel Buffer)]
        E4[(Virtual Channel Buffer)]
        E5[(Master Channel Buffer)]

        E6[ ] -->|"logical calling order of main services"| E7[ ]
        E8[ ] -.->|"push object to buffer"| E9[ ]
        E10[ ] -.-x|"pop object from buffer"| E11[ ]
        E12[ ] -.-|"other action related to this buffer"| E13[ ]

        style E1 height:0px;
        style E2 height:0px;
        style E3 height:0px;
        style E4 height:0px;
        style E5 height:0px;
    end

map4[("packetLengthBufferTxTcTypeAD (uint16_t)")]
map5[("packetBufferTxTcTypeAD (uint8_t)")]
map6[("packetLengthBufferTxTcTypeBD (uint16_t)")]
map7[("packetBufferTxTcTypeBD (uint8_t)")]
map8[("framesAfterSDLSProcessingTypeBDRxTC (frameTC*)")]
map9[("framesAfterSDLSProcessingTypeBDRxTC (frameTC*)")]


vc1[("framesAfterMCReceptionRxTM (frameTM*)")]
vc3[("inFramesBeforeVcReceptionRxTC (frameTC*)")]
vc6[("inFramesAfterVCReceptionTypeADRxTC (frameTC*)")]
vc21[("inFramesAfterVCReceptionTypeBDRxTC (frameTC*)")]
vc7[("unprocessedFrameListBufferTxTC (frameTC*)")]
vc8[("packetLengthBufferTxTM (uint16_t)")]
vc9[("packetBufferTxTM (uint8_t)")]
vc10[("packetLengthBufferTxTcTypeAD (uint16_t)")]
vc11[("packetBufferTxTcTypeAD (uint8_t)")]
vc12[("packetLengthBufferTxTcTypeBD (uint16_t)")]
vc13[("packetBufferTxTcTypeBD (uint8_t)")]
vc16[("framesBeforeSDLSProcessingTxTC (frameTC*)")]
vc17[("framesAfterSDLSProcessingTypeADRxTC (frameTC*)")]
vc19[("framesAfterSDLSProcessingTypeBDRxTC (frameTC*)")]

master1[("outFramesBeforeAllFramesGenerationListTxTC (frameTC*)")]
master4[("toBeTransmittedFramesAfterMCGenerationListTxTM (frameTM*)")]
master11[("framesAfterVcGenerationServiceTxTM (frameTM*)")]
master12[("masterCopyTxTC (frame TC)")]
master13[("masterCopyTxTM (frameTM)")]
master14[("masterCopyRxTC (frame TC)")]
master15[("masterCopyRxTM (frameTM)")]
master16[("masterChannelPoolTxTC (uint8_t)<br>Note: Stores transfer frame data of masterCopyTxTC frames")]
master17[("masterChannelPoolTxTM (uint8_t)<br>Note: Stores transfer frame data of masterCopyTxTM frames")]
master18[("virtualChannelCLCWQueues (CLCW)<br>(map of clcw queues for each virtual channel)")]
master19[("virtualChannelCLCWQueues (CLCW)<br>(map of clcw queues for each virtual channel)")]
master20[("masterChannelPoolRxTC (uint8_t)<br>Note: Stores transfer frame data of masterCopyRxTC frames")]

classDef map_channel_buffer fill:#3d8215;
classDef virtual_channel_buffer fill:#a6161f;
classDef master_channel_buffer fill:#244fb5;
classDef main_services fill:#B06F2A;
classDef utility_services fill:#648D98;

class map4,map5,map6,map7,map8,map9,E3 map_channel_buffer;
class vc1,vc2,vc3,vc4,vc6,vc21,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc16,vc17,vc19,E4 virtual_channel_buffer;
class master1,master4,master11,master12,master13,master14,master15,master16,master17,master18,master19,master20,E5 master_channel_buffer
class A1s1,A1s2,A2s1,A3s1,A4s1,A4s2,B1s1,B1s2,B2s1,B3s1,B4s1,C1s1,C2s1,C3s1,C4s1,D1s1,D2s1,E1 main_services;
class A1s3,A1s4,A1s5,A1s6,A1s7,A3s2,A4s3,A4s4,B1s4,B1s5,B1s6,B1s7,B2s2,B2s3,B2s4,C1s2,C1s3,C2s2,C2s3,C2s4,C4s2,D1s2,D1s3,E2 utility_services;
