#ifndef CCSDS_ALERT_HPP
#define CCSDS_ALERT_HPP

enum ServiceChannelAlert{
    NO_EVENT = 0,
    MAP_CHANNEL_FRAME_BUFFER_FULL = 1,
    VIRTUAL_CHANNEL_FRAME_BUFFER_FULL = 2,
    MASTER_CHANNEL_FRAME_BUFFER_FULL = 3,
    NO_PACKETS_TO_PROCESS = 4,
    PACKET_EXCEEDS_MAX_SIZE = 5,
};

#endif //CCSDS_ALERT_HPP
