#pragma once

enum ServiceChannelNotification : int {
	NO_SERVICE_EVENT = 0x01,
	MAP_CHANNEL_FRAME_BUFFER_FULL = 0x02,
	MASTER_CHANNEL_FRAME_BUFFER_FULL = 0x03,
	VC_MC_FRAME_BUFFER_FULL = 0x04,
	TX_MC_FRAME_BUFFER_FULL = 0x05,
	NO_TX_PACKETS_TO_PROCESS = 0x06,
	NO_RX_PACKETS_TO_PROCESS = 0x07,
	PACKET_EXCEEDS_MAX_SIZE = 0x08,
	TX_TO_BE_TRANSMITTED_FRAMES_LIST_EMPTY = 0x0A,
	TX_TO_BE_TRANSMITTED_FRAMES_LIST_FULL = 0x0B,
	RX_IN_MC_FULL = 0x0D,
	RX_IN_BUFFER_FULL = 0x0E,
	RX_OUT_BUFFER_FULL = 0x0F,
	RX_INVALID_TFVN = 0x10,
	RX_INVALID_SCID = 0x11,
	RX_INVALID_LENGTH = 0x12,
	VC_RX_WAIT_QUEUE_FULL = 0x13,
	VC_MC_FRAME_BUFFER_EMPTY = 0x15,
	INVALID_VC_ID = 0x16,
	INVALID_MAP_ID = 0x17,
	RX_INVALID_CRC = 0x1A,
	INVALID_SERVICE_CALL = 0x1B,
	PACKET_BUFFER_EMPTY = 0x1C,
	NO_TX_PACKETS_TO_TRANSFER_FRAME = 0x1D,
	MC_RX_INVALID_COUNT = 0x1E,
	MEMORY_POOL_FULL = 0x1F,
    INVALID_INPUT = 0x20,
    SDLS_ERROR = 0X21
};

enum SynchronizationFlag : bool {
    OCTET_SYNCHRONIZED_FORWARD_ORDERED = false,
    VCA_SDU = true
};

enum VirtualChannelAlert : uint8_t {
	NO_VC_ALERT = 0x01,
	UNPROCESSED_PACKET_LIST_FULL = 0x02,
	TX_WAIT_QUEUE_FULL = 0x03,
	RX_WAIT_QUEUE_FULL = 0x04,
};

enum MasterChannelAlert : uint8_t {
	NO_MC_ALERT = 0x01,
	OUT_FRAMES_LIST_FULL = 0x02,
	TO_BE_TRANSMITTED_FRAMES_LIST_FULL = 0x03,
	MAX_AMOUNT_OF_VIRT_CHANNELS = 0x04,
	NO_SPACE = 0x05
};

enum SDLSVerificationStatusCode {
    NO_FAILURE = 0x01,
    INVALID_SPI = 0x02,
    INVALID_FRAME_TYPE = 0x03,
    UNASSOCIATED_CHANNEL = 0x04,
    INVALID_USER = 0x05,
    MAC_CALCULATION_ERROR = 0x06,
    MAC_VERIFICATION_FAILURE = 0x07,
    ANTI_REPLAY_SEQUENCE_NUMBER_FAILURE = 0x08,
    PADDING_ERROR = 0x09
};

enum TxRx : uint8_t { Rx = 0x00, Tx = 0x01 };

enum NotificationType : uint8_t {
	TypeVirtualChannelAlert = 0x00,
	TypeMasterChannelAlert = 0x01,
	TypeServiceChannelNotif = 0x02,
	TypeFDURequestType = 0x05,
    TypeSDLSVerificationStatusCode = 0x06
};
