#ifndef CCSDS_TM_PACKETS_TRANSFERFRAME_HPP
#define CCSDS_TM_PACKETS_TRANSFERFRAME_HPP

#include "CCSDS_Definitions.hpp"

class CCSDSTransferFrame {

};

#endif // CCSDS_TM_PACKETS_CCSDSTRANSFERFRAME_HPP
