/*
 * All necessary definitions used throughout the program
 */

#ifndef CCSDS_CCSDS_DEFINITIONS_HPP
#define CCSDS_CCSDS_DEFINITIONS_HPP

#define SPACECRAFT_IDENTIFIER 567U // A 10-bit unique identifier, assigned by the SANA

/* TM Packet Definitions */
#define TM_TRANSFER_FRAME_SIZE 128U
#define TM_PRIMARY_HEADER_SIZE 6U
#define TM_SECONDARY_HEADER_SIZE 0U // Size set to zero if the secondary header is not used

#define TM_OPERATIONAL_CONTROL_FIELD_EXISTS 0
#define TM_ERROR_CONTROL_FIELD_EXISTS 0

#if TM_ERROR_CONTROL_FIELD_EXISTS && TM_OPERATIONAL_CONTROL_FIELD_EXISTS
#define TM_FRAME_DATA_FIELD_SIZE (TM_TRANSFER_FRAME_SIZE - TM_PRIMARY_HEADER_SIZE - TM_SECONDARY_HEADER_SIZE - 6) // Ignore-MISRA
#elif TM_OPERATIONAL_CONTROL_FIELD_EXISTS
#define TM_FRAME_DATA_FIELD_SIZE (TM_TRANSFER_FRAME_SIZE - TM_PRIMARY_HEADER_SIZE - TM_SECONDARY_HEADER_SIZE - 4) // Ignore-MISRA
#elif TM_ERROR_CONTROL_FIELD_EXISTS
#define TM_FRAME_DATA_FIELD_SIZE (TM_TRANSFER_FRAME_SIZE - TM_PRIMARY_HEADER_SIZE - TM_SECONDARY_HEADER_SIZE - 2) // Ignore-MISRA
#else
#define TM_FRAME_DATA_FIELD_SIZE (TM_TRANSFER_FRAME_SIZE - TM_PRIMARY_HEADER_SIZE - TM_SECONDARY_HEADER_SIZE) // Ignore-MISRA
#endif

#define TM_MAX_PACKET_SIZE 32768U // TODO: Check whether this is defined in ECSS of OBC

/* TC Packet Definitions */

#define TC_PRIMARY_HEADER_SIZE 5U
#define TC_ERROR_CONTROL_FIELD_EXISTS 0
#define TC_SEGMENT_HEADER_EXISTS 0

#define TC_MAX_TRANSFER_FRAME_SIZE 1024U

#if TC_ERROR_CONTROL_FIELD_EXISTS
#define TC_MAX_DATA_FIELD_SIZE 1017
#else
#define TC_MAX_DATA_FIELD_SIZE 1019
#endif

#endif // CCSDS_TCCSDS_DEFINITIONS_HPP
